### ISSUE TITLE
Sandbox security?

### ISSUE THREAD

**Issue by mweichert** [Cron-Near/croncat#15]
Hi there,

I'm quite interested in Croncats. The ecosystem needs a decentralized cron service. One question I had was related to security and the notion of tasks running in a sandbox.

How can I assure that the parameters of my task aren't tampered with?

**Comment by TrevorJTClarke** [comment]
Hello @mweichert take a look here: https://github.com/Cron-Near/contracts/blob/main/manager/src/tasks.rs#L161

This method doesnt not allow execution with tampered parameters, and the agent has no way to dictate which task gets executed.
