### ISSUE TITLE
Function "implicitAccountId" referenced but not defined

### ISSUE THREAD

**Issue by t-ilk** [Cron-Near/croncat#21]
At ln. 37 in `near.js` there is the following assignment:

```js
    const id = accountId || implicitAccountId(publicKey)
```

However, `implicitAccountId` is declared nowhere.

If this is what you have intended, I can change this part as below, and open a PR for that:

```js
const id = accountId
```

**Comment by TrevorJTClarke** [comment]
ah, i must have removed at one point -- good catch. Feel free to open PR
