### ISSUE TITLE
Change croncat status 'Wallet Balance' and 'Rewards Balance'

### ISSUE THREAD

**Issue by bentleybm** [Cron-Near/croncat#23]
croncat status to display **Rewards Balance** and **Wallet Balance** as separate line values.

**Comment by TrevorJTClarke** [comment]
![Screenshot from 2021-12-03 22-12-18](https://user-images.githubusercontent.com/2633184/144699791-0e2556ec-2bc6-4543-82d5-7f321943cf6b.png)

Done, thanks!
